# Generated by Django 4.2.9 on 2024-01-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
